include: package:flutter_lints/flutter.yaml
linter:
  rules:
    avoid_relative_lib_imports: false
    prefer_relative_imports: true
    prefer_single_quotes: true
  # avoid_print: false  # Uncomment to disable the `avoid_print` rule
