name: my_flutter_app_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.1.4
  flutter: 
    sdk: flutter

#  containers app
  app_auth:
    path: ./lib/app/containers/app_auth
  app_home:
    path: ./lib/app/containers/app_home

dev_dependencies:
#  lints: ^1.0.1
  flutter_lints: ^1.0.3
  flutter_test:
    sdk: flutter
flutter: 
  uses-material-design: true

